name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            if [ -d '${{ secrets.PROJECT_PATH }}' ]; then
              cd ${{ secrets.PROJECT_PATH }} &&
              git fetch origin &&
              git reset --hard origin/main
            else
              git clone ${{ secrets.REPO_URL }} ${{ secrets.PROJECT_PATH }}
              cd ${{ secrets.PROJECT_PATH }}
            fi &&
            bun install &&
            bun run build &&
            bun run start -p ${{ secrets.SERVER_PORT }}
          "
