name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh root@${{ secrets.SERVER_IP }} "}"
            export PATH=/root/.bun/bin:$PATH;
            cd ${{ secrets.PROJECT_PATH }} || git clone ${{ secrets.REPO_URL }} ${{ secrets.PROJECT_PATH }};
            cd ${{ secrets.PROJECT_PATH }};
            git pull origin main;
            pid=$(lsof -t -i:${{ secrets.SERVER_PORT }}) && kill -9 $pid || true;
            bun install;
            bun run build;
            if nohup bun run start -p ${{ secrets.SERVER_PORT }} > app.log 2>&1 & then
              echo 'Application started successfully'
              exit 0
            else
              echo 'Failed to start application'
              exit 1
            fi
          "
