name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh root@${{ secrets.SERVER_IP }} "
            export PATH=/root/.bun/bin:$PATH;
            cd ${{ secrets.PROJECT_PATH }} || git clone ${{ secrets.REPO_URL }} ${{ secrets.PROJECT_PATH }};
            cd ${{ secrets.PROJECT_PATH }};
            git pull origin main;
            pid=$(lsof -t -i:${{ secrets.PORT }}) && kill -9 $pid || true;
            bun install;
            bun run build;
            nohup bun run start -p ${{ secrets.PORT }} > app.log 2>&1 &
            echo 'Application started successfully'
          "
